_target_: app_config.AppConfig

docling_config:
  _target_: app_config.docling_config.DoclingConfig
  ocr_config:
    _target_: app_config.docling_config.ocr_config.ThreadedStandardOCRConfig
    languages: ["eng"]
    force_full_page_ocr: true
    ocr_engine: tesseract_cli_ocr
    # Enrichments
    do_formula_enrichment: false
    do_table_structure: true
    do_code_enrichment: false

  generate_page_images: true
  images_scale: 2.0

  # Enrichments
  picture_desc_config:
    # _target_: app_config.docling_config.picture_desc_config.PictureDescriptionVlmConfig
    # repo_id: "ibm-granite/granite-docling-258M"
    # prompt: "Describe this image in a few sentences."
    # generation_config:
    #   min_tokens: 100
    #   max_new_tokens: 200
    #   do_sample: false
    _target_: app_config.docling_config.picture_desc_config.PictureDescriptionApiConfig
    url: "${oc.env:OLLAMA_HOST,http://localhost:11434/}v1/chat/completions"
    prompt: "Describe this image in detail. Don't miss out any details."
    params:
      model: granite3.2-vision:2b
      # model: gemma3:4b
      # model: gemma3:12b
      # model: openbmb/minicpm-v4.5
      # model: openbmb/minicpm-o2.6
      temperature: 0
    timeout: 1800

  formula_analyser: null

tokenizer_config:
  _target_: app_config.tokenizer_config.HuggingfaceTokenizerConfig
  model: "onnx-community/embeddinggemma-300m-ONNX"
  max_tokens: 1024

embedding_config:
  _target_: app_config.embedding_config.OllamaEmbeddingConfig
  model: "embeddinggemma:300m"
  base_url: "${oc.env:OLLAMA_HOST,http://localhost:11434/}"

vector_store_config:
  _target_: app_config.vector_store_config.QdrantVectorStoreConfig
  url: http://localhost:6333
  collection_name: default
