_target_: app_config.AppConfig

docling_config:
  _target_: app_config.docling_config.DoclingConfig
  ocr_config:
    _target_: app_config.docling_config.ocr_config.ThreadedStandardOCRConfig
    languages: ["eng"]
    force_full_page_ocr: true
    ocr_engine: tesseract_cli_ocr
    # Enrichments
    do_formula_enrichment: false
    do_table_structure: true
    do_code_enrichment: false

  generate_page_images: true
  # images_scale: 2.0
  images_scale: 1.0

  # Enrichments
  picture_desc_config:
    _target_: app_config.docling_config.picture_desc_config.PictureDescriptionApiConfig
    url: "${oc.env:PICTURE_DESC_OLLAMA_HOST,http://localhost:11434/}v1/chat/completions"
    prompt: "${read_file:assets/prompts/${oc.env:CUSTOM_PICTURE_DESC_MODEL,qwen2.5vl:7b}/picture_desc_prompt.txt}"
    params:
      model: "${oc.env:CUSTOM_PICTURE_DESC_MODEL,qwen2.5vl:7b}"
      temperature: 0
    timeout: 1800

  formula_analyser: null
  text_analyser:
    _target_: app_config.docling_config.text_enhancer_pipeline.TextEnhancerAnalyserOpenAIApi
    allow_label_expr: "label != 'formula'"
    url: "${oc.env:TEXT_ANALYSER_OLLAMA_HOST,http://localhost:11434/}v1/chat/completions"
    prompt: "${read_file:assets/prompts/${oc.env:CUSTOM_TEXT_ANALYSER_MODEL,qwen2.5vl:7b}/text_analyser_prompt.txt}"
    params:
      model: "${oc.env:CUSTOM_TEXT_ANALYSER_MODEL,qwen2.5vl:3b}"
      temperature: 0
    concurrency: 1
    timeout: 1800  # 30 minutes

tokenizer_config:
  _target_: app_config.tokenizer_config.HuggingfaceTokenizerConfig
  model: "onnx-community/embeddinggemma-300m-ONNX"
  max_tokens: 1024

embedding_config:
  _target_: app_config.embedding_config.OllamaEmbeddingConfig
  model: "embeddinggemma:300m"
  base_url: "${oc.env:EMBEDDING_OLLAMA_HOST,http://localhost:11434/}"

vector_store_config:
  _target_: app_config.vector_store_config.QdrantVectorStoreConfig
  url: http://localhost:6333
  collection_name: default
