_target_: app_config.AppConfig

docling_config:
  _target_: app_config.docling_config.DoclingConfig
  ocr_config:
    _target_: app_config.docling_config.ocr_config.ThreadedStandardOCRConfig
    languages: ["eng"]
    force_full_page_ocr: true
    ocr_engine: tesseract_cli_ocr
    # Enrichments
    do_formula_enrichment: false
    do_table_structure: true
    do_code_enrichment: false

  generate_page_images: true
  # images_scale: 2.0
  images_scale: 1.0

  # Enrichments
  picture_desc_analyser:
    _target_: app_config.docling_config.picture_desc_pipeline.PictureDescriptionAnalyserOpenAIApi
    url: "${oc.env:PICTURE_DESC_OLLAMA_HOST,http://localhost:11434/}v1/chat/completions"
    prompt: "${read_file:assets/prompts/picture_desc_prompt.txt}"
    params:
      model: "${oc.env:CUSTOM_PICTURE_DESC_MODEL,qwen2.5vl:7b}"
      temperature: 0
    timeout: 1800
    retry_config:
      _target_: utils.retry.RetryConfig
      max_retries: 3
      base_delay: 10
      strategy: "exponential"
      jitter: true
    # min_time_per_request_in_seconds: 60  # For throttling. Will be useful when using APIs from external providers.

  formula_analyser: null
  text_analyser:
    _target_: app_config.docling_config.text_enhancer_pipeline.TextEnhancerAnalyserOpenAIApi
    allow_label_expr: "label != 'formula'"
    url: "${oc.env:TEXT_ANALYSER_OLLAMA_HOST,http://localhost:11434/}v1/chat/completions"
    prompt: "${read_file:assets/prompts/text_analyser_prompt.txt}"
    params:
      model: "${oc.env:CUSTOM_TEXT_ANALYSER_MODEL,qwen2.5vl:3b}"
      temperature: 0
    concurrency: 1
    timeout: 1800  # 30 minutes
    retry_config:
      _target_: utils.retry.RetryConfig
      max_retries: 3
      base_delay: 10
      strategy: "exponential"
      jitter: true
    # min_time_per_request_in_seconds: 60  # For throttling. Will be useful when using APIs from external providers.
    suppress_errors: True

tokenizer_config:
  _target_: app_config.tokenizer_config.HuggingfaceTokenizerConfig
  model: "${oc.env:HF_EMBEDDING_MODEL,Qwen/Qwen3-Embedding-4B}"
  max_tokens: 1024

embedding_config:
  # _target_: app_config.embedding_config.HuggingFaceEmbeddingsConfig
  # model_name: "${oc.env:HF_EMBEDDING_MODEL,Qwen/Qwen3-Embedding-4B}"
  _target_: app_config.embedding_config.OllamaEmbeddingConfig
  model: "${oc.env:OLLAMA_EMBEDDING_MODEL,qwen3-embedding:4b}"
  base_url: "${oc.env:OLLAMA_HOST,http://localhost:11434/}"

vector_store_config:
  _target_: app_config.vector_store_config.QdrantVectorStoreConfig
  client_opts:
    url: http://localhost:6333
  collection_name: default
  retriever_kwargs:
    search_type: "mmr"
    search_kwargs:
        k: 5
        fetch_k: 20

reranking_embedding_config:
  _target_: app_config.embedding_config.OllamaEmbeddingConfig
  model: "${oc.env:RERANKING_OLLAMA_EMBEDDING_MODEL,qwen3-embedding:8b}"
  base_url: "${oc.env:EMBEDDING_OLLAMA_HOST,http://localhost:11434/}"
