docling_config:
  ocr_config:
    _target_: app_config.docling_config.ocr_config.ThreadedStandardOCRConfig
    languages: ["eng", "equ"]
    force_full_page_ocr: true
    ocr_engine: tesseract_cli_ocr
    do_formula_enrichment: true
    do_table_structure: true

  formula_analyser:
    _target_: app_config.docling_config.formula_understanding_pipeline.FormulaUnderstandingAnalyserRapidLatexOCRCli
    timeout: 1800  # 30 minutes

vector_store_config:
  collection_name: math
