docling_config:
  ocr_config:
    _target_: app_config.docling_config.ocr_config.ThreadedStandardOCRConfig
    languages: ["eng", "equ"]
    force_full_page_ocr: true
    ocr_engine: tesseract_cli_ocr
    do_formula_enrichment: true
    do_table_structure: true

  formula_analyser:
    _target_: app_config.docling_config.formula_understanding_pipeline.FormulaUnderstandingAnalyserRapidLatexOCRCli
    timeout: 1800  # 30 minutes

  text_analyser:
    _target_: app_config.docling_config.text_enhancer_pipeline.TextEnhancerAnalyserOpenAIApi
    allow_label_expr: "label != 'formula'"
    url: "${oc.env:OLLAMA_HOST,http://localhost:11434/}v1/chat/completions"
    prompt: "Extract text from this image. If no text in image, then output nothing. Don't add any explanation or description, just output the content of the image."
    params:
      model: qwen2.5vl:3b
      temperature: 0
    concurrency: 1
    timeout: 1800  # 30 minutes

vector_store_config:
  collection_name: math
